In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("dataset/multi_criteria_routing_data.csv")

In [3]:
dataset.sample(5)

,Route_ID,Source_Node,Destination_Node,Latency_ms,Bandwidth_Mbps,Security_Risk,Energy_Consumption_J,Packet_Delivery_Ratio_%,End_to_End_Delay_ms,Trust_Score,Algorithm_Used,Optimal
285,R286,14,21,24.274459,59.842202,0.141972,8.577439,98.725612,20.318520,0.540299,Traditional,0
191,R192,19,37,79.144607,80.247296,0.806404,2.401808,91.980892,7.564043,0.765363,Traditional,0
443,R444,13,35,50.708646,17.395450,0.992817,6.520682,84.353348,16.378615,0.970940,MCRO-RHGSO,0
432,R433,17,28,58.716670,36.688202,0.293489,9.681085,86.423243,49.260524,0.586624,MCRO-RHGSO,0
159,R160,17,39,13.330687,38.017693,0.198098,7.414570,83.979843,17.526582,0.671271,Traditional,0

In [4]:
dataset.groupby(["Source_Node", "Destination_Node"])["Route_ID"].count().reset_index(name="count").sort_values(by="count", ascending=False).head(10)

     Source_Node  Destination_Node  count
242           18                35      6
103            7                39      5
119            9                21      5
145           11                32      5
39             3                34      5
21             2                28      5
0              1                21      4
187           14                36      4
206           16                26      4
42             3                37      4

In [5]:
dataset[dataset["Optimal"] == 1]

,Route_ID,Source_Node,Destination_Node,Latency_ms,Bandwidth_Mbps,Security_Risk,Energy_Consumption_J,Packet_Delivery_Ratio_%,End_to_End_Delay_ms,Trust_Score,Algorithm_Used,Optimal
42,R43,3,30,46.847049,15.137817,0.368310,2.220294,99.336910,21.219207,0.978355,MCRO-RHGSO,1
69,R70,9,38,34.664970,97.292084,0.058551,6.429692,85.306523,20.385738,0.757283,MCRO-RHGSO,1
109,R110,14,22,40.081950,83.605079,0.186101,4.206141,88.753227,11.916097,0.832364,MCRO-RHGSO,1
145,R146,9,24,26.251781,68.272724,0.347343,2.152929,94.653981,8.829657,0.886086,MCRO-RHGSO,1
193,R194,9,21,47.922130,84.035289,0.051957,5.222986,92.970096,25.629414,0.865562,MCRO-RHGSO,1
196,R197,7,23,19.942670,18.598178,0.258621,4.248036,99.300307,35.024555,0.979152,MCRO-RHGSO,1
245,R246,7,22,18.233815,99.472543,0.440323,4.881871,94.774463,30.055321,0.917268,MCRO-RHGSO,1
256,R257,19,23,46.760789,58.224492,0.165955,7.496154,81.622984,44.180107,0.945925,MCRO-RHGSO,1
273,R274,9,28,34.032544,18.021199,0.471168,2.385488,85.377070,39.225904,0.918398,MCRO-RHGSO,1
418,R419,18,31,17.072065,56.656722,0.196098,9.958554,84.069455,49.125570,0.803012,MCRO-RHGSO,1

In [6]:
dataset = dataset[(dataset["Source_Node"] == 9) & (dataset["Destination_Node"] == 21)]
dataset

,Route_ID,Source_Node,Destination_Node,Latency_ms,Bandwidth_Mbps,Security_Risk,Energy_Consumption_J,Packet_Delivery_Ratio_%,End_to_End_Delay_ms,Trust_Score,Algorithm_Used,Optimal
193,R194,9,21,47.922130,84.035289,0.051957,5.222986,92.970096,25.629414,0.865562,MCRO-RHGSO,1
294,R295,9,21,83.617032,86.628246,0.979105,4.362412,89.821915,24.718038,0.388726,Traditional,0
415,R416,9,21,17.907985,67.300271,0.971533,9.685016,87.756522,30.958582,0.871913,Traditional,0
474,R475,9,21,48.294400,31.662344,0.668573,4.856969,94.327942,34.538432,0.353103,Traditional,0
484,R485,9,21,88.608091,32.701692,0.120558,6.047663,81.539433,8.456137,0.605090,Traditional,0

In [7]:
dataset = dataset[["Latency_ms", "Bandwidth_Mbps", "Energy_Consumption_J", "Packet_Delivery_Ratio_%"]]
dataset

     Latency_ms  Bandwidth_Mbps  Energy_Consumption_J  Packet_Delivery_Ratio_%
193   47.922130       84.035289              5.222986                92.970096
294   83.617032       86.628246              4.362412                89.821915
415   17.907985       67.300271              9.685016                87.756522
474   48.294400       31.662344              4.856969                94.327942
484   88.608091       32.701692              6.047663                81.539433

In [8]:
dataset = dataset.to_numpy()
dataset

array([[47.9221302 , 84.03528867,  5.22298626, 92.9700964 ],
       [83.61703217, 86.6282462 ,  4.36241182, 89.82191459],
       [17.90798492, 67.3002714 ,  9.6850158 , 87.7565218 ],
       [48.2944001 , 31.66234406,  4.85696927, 94.32794224],
       [88.60809143, 32.70169182,  6.04766326, 81.53943339]])